// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI flow for generating engaging content captions including hooks, CTAs, hashtags, and captions.
 *
 * - generateContentCaptions - A function that generates content captions.
 * - GenerateContentCaptionsInput - The input type for the generateContentCaptions function.
 * - GenerateContentCaptionsOutput - The return type for the generateContentCaptions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateContentCaptionsInputSchema = z.object({
  topic: z.string().describe('The topic of the content.'),
  keywords: z.string().describe('Relevant keywords for the content.'),
  tone: z.string().describe('The desired tone of the content (e.g., funny, serious, informative).'),
  platform: z.string().describe('The social media platform for the content (e.g., Instagram, TikTok, X).'),
});

export type GenerateContentCaptionsInput = z.infer<typeof GenerateContentCaptionsInputSchema>;

const GenerateContentCaptionsOutputSchema = z.object({
  hook: z.string().describe('An engaging hook for the content.'),
  cta: z.string().describe('A clear call to action for the content.'),
  hashtags: z.string().describe('Relevant hashtags for the content.'),
  caption: z.string().describe('A full caption for the content.'),
});

export type GenerateContentCaptionsOutput = z.infer<typeof GenerateContentCaptionsOutputSchema>;

export async function generateContentCaptions(input: GenerateContentCaptionsInput): Promise<GenerateContentCaptionsOutput> {
  return generateContentCaptionsFlow(input);
}

const generateContentCaptionsPrompt = ai.definePrompt({
  name: 'generateContentCaptionsPrompt',
  input: {schema: GenerateContentCaptionsInputSchema},
  output: {schema: GenerateContentCaptionsOutputSchema},
  prompt: `You are a social media expert. Generate engaging content for the following topic, keywords, tone, and platform.

Topic: {{{topic}}}
Keywords: {{{keywords}}}
Tone: {{{tone}}}
Platform: {{{platform}}}

Generate a hook, call to action, hashtags, and a full caption optimized for the specified platform and tone. Make sure it is eye catching, interesting, and makes the user want to know more.

Hook:
{{hook}}

CTA:
{{cta}}

Hashtags:
{{hashtags}}

Caption:
{{caption}}`,
});

const generateContentCaptionsFlow = ai.defineFlow(
  {
    name: 'generateContentCaptionsFlow',
    inputSchema: GenerateContentCaptionsInputSchema,
    outputSchema: GenerateContentCaptionsOutputSchema,
  },
  async input => {
    const {output} = await generateContentCaptionsPrompt(input);
    return output!;
  }
);
